/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedProfilesRouteImport } from './routes/_authenticated/profiles'
import { Route as UnauthenticatedSignInRouteImport } from './routes/_unauthenticated/sign-in'
import { Route as ApiProfilePictureRouteImport } from './routes/api/profile-picture'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthenticatedAuthorizedAppsIndexRouteImport } from './routes/_authenticated/authorized-apps.index'
import { Route as AuthenticatedAuthorizedAppsClientIdRouteImport } from './routes/_authenticated/authorized-apps.$clientId'
import { Route as UnauthenticatedSignUpIndexRouteImport } from './routes/_unauthenticated/sign-up/index'
import { Route as UnauthenticatedSignUpDeveloperRouteImport } from './routes/_unauthenticated/sign-up/developer'
import { Route as UnauthenticatedSignUpIdentityHolderRouteImport } from './routes/_unauthenticated/sign-up/identity-holder'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilesRoute = AuthenticatedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedSignInRoute = UnauthenticatedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const ApiProfilePictureRoute = ApiProfilePictureRouteImport.update({
  id: '/api/profile-picture',
  path: '/api/profile-picture',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthorizedAppsIndexRoute =
  AuthenticatedAuthorizedAppsIndexRouteImport.update({
    id: '/authorized-apps/',
    path: '/authorized-apps/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuthorizedAppsClientIdRoute =
  AuthenticatedAuthorizedAppsClientIdRouteImport.update({
    id: '/authorized-apps/$clientId',
    path: '/authorized-apps/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const UnauthenticatedSignUpIndexRoute =
  UnauthenticatedSignUpIndexRouteImport.update({
    id: '/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignUpDeveloperRoute =
  UnauthenticatedSignUpDeveloperRouteImport.update({
    id: '/sign-up/developer',
    path: '/sign-up/developer',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignUpIdentityHolderRoute =
  UnauthenticatedSignUpIdentityHolderRouteImport.update({
    id: '/sign-up/identity-holder',
    path: '/sign-up/identity-holder',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/sign-in': typeof UnauthenticatedSignInRoute
  '/api/profile-picture': typeof ApiProfilePictureRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/authorized-apps/$clientId': typeof AuthenticatedAuthorizedAppsClientIdRoute
  '/sign-up/developer': typeof UnauthenticatedSignUpDeveloperRoute
  '/sign-up/identity-holder': typeof UnauthenticatedSignUpIdentityHolderRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authorized-apps/': typeof AuthenticatedAuthorizedAppsIndexRoute
  '/sign-up/': typeof UnauthenticatedSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/sign-in': typeof UnauthenticatedSignInRoute
  '/api/profile-picture': typeof ApiProfilePictureRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/authorized-apps/$clientId': typeof AuthenticatedAuthorizedAppsClientIdRoute
  '/sign-up/developer': typeof UnauthenticatedSignUpDeveloperRoute
  '/sign-up/identity-holder': typeof UnauthenticatedSignUpIdentityHolderRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/authorized-apps': typeof AuthenticatedAuthorizedAppsIndexRoute
  '/sign-up': typeof UnauthenticatedSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profiles': typeof AuthenticatedProfilesRoute
  '/_unauthenticated/sign-in': typeof UnauthenticatedSignInRoute
  '/api/profile-picture': typeof ApiProfilePictureRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/authorized-apps/$clientId': typeof AuthenticatedAuthorizedAppsClientIdRoute
  '/_unauthenticated/sign-up/developer': typeof UnauthenticatedSignUpDeveloperRoute
  '/_unauthenticated/sign-up/identity-holder': typeof UnauthenticatedSignUpIdentityHolderRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/authorized-apps/': typeof AuthenticatedAuthorizedAppsIndexRoute
  '/_unauthenticated/sign-up/': typeof UnauthenticatedSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/history'
    | '/profiles'
    | '/sign-in'
    | '/api/profile-picture'
    | '/oauth/consent'
    | '/authorized-apps/$clientId'
    | '/sign-up/developer'
    | '/sign-up/identity-holder'
    | '/api/auth/$'
    | '/authorized-apps/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/history'
    | '/profiles'
    | '/sign-in'
    | '/api/profile-picture'
    | '/oauth/consent'
    | '/authorized-apps/$clientId'
    | '/sign-up/developer'
    | '/sign-up/identity-holder'
    | '/api/auth/$'
    | '/authorized-apps'
    | '/sign-up'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/_authenticated/history'
    | '/_authenticated/profiles'
    | '/_unauthenticated/sign-in'
    | '/api/profile-picture'
    | '/oauth/consent'
    | '/_authenticated/'
    | '/_authenticated/authorized-apps/$clientId'
    | '/_unauthenticated/sign-up/developer'
    | '/_unauthenticated/sign-up/identity-holder'
    | '/api/auth/$'
    | '/_authenticated/authorized-apps/'
    | '/_unauthenticated/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiProfilePictureRoute: typeof ApiProfilePictureRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/sign-in': {
      id: '/_unauthenticated/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthenticatedSignInRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/api/profile-picture': {
      id: '/api/profile-picture'
      path: '/api/profile-picture'
      fullPath: '/api/profile-picture'
      preLoaderRoute: typeof ApiProfilePictureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/authorized-apps/': {
      id: '/_authenticated/authorized-apps/'
      path: '/authorized-apps'
      fullPath: '/authorized-apps/'
      preLoaderRoute: typeof AuthenticatedAuthorizedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authorized-apps/$clientId': {
      id: '/_authenticated/authorized-apps/$clientId'
      path: '/authorized-apps/$clientId'
      fullPath: '/authorized-apps/$clientId'
      preLoaderRoute: typeof AuthenticatedAuthorizedAppsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/sign-up/': {
      id: '/_unauthenticated/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof UnauthenticatedSignUpIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/sign-up/developer': {
      id: '/_unauthenticated/sign-up/developer'
      path: '/sign-up/developer'
      fullPath: '/sign-up/developer'
      preLoaderRoute: typeof UnauthenticatedSignUpDeveloperRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/sign-up/identity-holder': {
      id: '/_unauthenticated/sign-up/identity-holder'
      path: '/sign-up/identity-holder'
      fullPath: '/sign-up/identity-holder'
      preLoaderRoute: typeof UnauthenticatedSignUpIdentityHolderRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfilesRoute: typeof AuthenticatedProfilesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuthorizedAppsClientIdRoute: typeof AuthenticatedAuthorizedAppsClientIdRoute
  AuthenticatedAuthorizedAppsIndexRoute: typeof AuthenticatedAuthorizedAppsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfilesRoute: AuthenticatedProfilesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuthorizedAppsClientIdRoute:
    AuthenticatedAuthorizedAppsClientIdRoute,
  AuthenticatedAuthorizedAppsIndexRoute: AuthenticatedAuthorizedAppsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedSignInRoute: typeof UnauthenticatedSignInRoute
  UnauthenticatedSignUpDeveloperRoute: typeof UnauthenticatedSignUpDeveloperRoute
  UnauthenticatedSignUpIdentityHolderRoute: typeof UnauthenticatedSignUpIdentityHolderRoute
  UnauthenticatedSignUpIndexRoute: typeof UnauthenticatedSignUpIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedSignInRoute: UnauthenticatedSignInRoute,
  UnauthenticatedSignUpDeveloperRoute: UnauthenticatedSignUpDeveloperRoute,
  UnauthenticatedSignUpIdentityHolderRoute:
    UnauthenticatedSignUpIdentityHolderRoute,
  UnauthenticatedSignUpIndexRoute: UnauthenticatedSignUpIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiProfilePictureRoute: ApiProfilePictureRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
